#!/usr/bin/env python3

import json
import os
import urllib.request
from distutils.version import LooseVersion as Version


PYPI_DOMAIN = "test.pypi.org" if os.getenv("TEST_PYPI") else "pypi.org"
PYPI_API_URL = f"https://{PYPI_DOMAIN}/pypi/ddgr/json"
GITHUB_API_URL = "https://api.github.com/repos/jarun/ddgr/releases"


def get_json(url):
    return json.loads(urllib.request.urlopen(url).read())


def main():
    pypi_latest_version = list(get_json(PYPI_API_URL)["releases"])[-1]
    github_latest_version = get_json(GITHUB_API_URL)[0]["tag_name"].lstrip("v")
    update_due = (
        "true"
        if Version(github_latest_version) > Version(pypi_latest_version)
        else "false"
    )
    print(f"PYPI_LATEST_VERSION: {pypi_latest_version}")
    print(f"GITHUB_LATEST_VERSION: {github_latest_version}")
    print(f"UPDATE_DUE: {update_due}")
    print(f"::set-env name=PYPI_LATEST_VERSION::{pypi_latest_version}")
    print(f"::set-env name=GITHUB_LATEST_VERSION::{github_latest_version}")
    print(f"::set-env name=UPDATE_DUE::{update_due}")


if __name__ == "__main__":
    main()
